// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fokapqhycaskymzchrrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZva2FwcWh5Y2Fza3ltemNocnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MjQ4ODIsImV4cCI6MjA3NTAwMDg4Mn0.cjWjZ7-IcIy9J655cSdVIu2KuewkvZZxQZXCv0rwIjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});